/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sys.view;

import br.com.sys.connection.ConnectionFactory;
import br.com.sys.model.bean.Divida;
import br.com.sys.model.bean.Pagamento;
import br.com.sys.model.dao.DividaDAO;
import br.com.sys.model.dao.PagamentoDAO;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ANDRE
 */
public class TelaFaturamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaFaturamento
     */
    public TelaFaturamento() {
        initComponents();
          DefaultTableModel modelo = (DefaultTableModel) tableFaturamento.getModel();
        tableFaturamento.setRowSorter(new TableRowSorter(modelo));
        readTable();
    }
         public void readTable() { 
        DefaultTableModel modelo = (DefaultTableModel) tableFaturamento.getModel();
        modelo.setNumRows(0);
        PagamentoDAO pdao = new PagamentoDAO();
        
        for (Pagamento p : pdao.read()) {
            modelo.addRow(new Object[]{
             
                p.getDivida(),
                p.getDataPagamento(),
                p.getValorPago(),
            });
        }
    }
       public void readTableConsulta(Date data_inicio, Date data_final) {
        
        DefaultTableModel modelo = (DefaultTableModel) tableFaturamento.getModel();
        modelo.setNumRows(0);
        PagamentoDAO pdao = new PagamentoDAO();

        for (Pagamento p : pdao.readForData(data_inicio, data_final)) {
            modelo.addRow(new Object[]{
                p.getDivida(),
                p.getDataPagamento(),
                p.getValorPago(),
            });
        }
    }

//    
//      public List<Pagamento> readForConsulta(){
//        Connection con = ConnectionFactory.getConnection();
//        PreparedStatement stmt = null;
//        ResultSet rs = null;
//        
//        List<Pagamento> fat = new ArrayList<>();
//        try {
//            stmt = con.prepareStatement("SELECT * FROM pagamento WHERE data_pagamento BETWEEN ? AND ?");
//            rs = stmt.executeQuery();
//            
//            while (rs.next()){
//                Pagamento pag = new Pagamento();
//                DividaDAO dao = new DividaDAO();
//                pag.setDivida(dao.readDivida(rs.getInt("divida")));
//                pag.setDataPagamento( rs.getDate("data_pagamento"));
//                pag.setValorPago(rs.getDouble("valor_pago"));
//                fat.add(pag);
//                
//                                     
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, "Erro ao listar os pagamentos: "+ex);
//        }finally{
//            ConnectionFactory.closeConnection(con, stmt, rs);
//        }
//        return fat;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFatDataDe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFatDataAte = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFaturamento = new javax.swing.JTable();
        btnPesq = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Faturamento");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sys/imagens/sisdebt 185x85.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Período:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("De ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Até");

        tableFaturamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Divida", "Data do Pagamento", "Valor Pago"
            }
        ));
        jScrollPane1.setViewportView(tableFaturamento);

        btnPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sys/imagens/searche.png"))); // NOI18N
        btnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqActionPerformed1(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFatDataDe, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFatDataAte, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtFatDataDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(txtFatDataAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesqActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqActionPerformed1
        try {
            // TODO add your handling code here:
            SimpleDateFormat formatDate = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date invoiceDate = formatDate.parse(txtFatDataDe.getText());
            java.sql.Date sqlDate = new java.sql.Date(invoiceDate.getTime());
            
            SimpleDateFormat formatDate2 = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date invoiceDate2 = formatDate2.parse(txtFatDataAte.getText());
            java.sql.Date sqlDate2 = new java.sql.Date(invoiceDate2.getTime());
            
            Pagamento p = new Pagamento();
            PagamentoDAO pdao = new PagamentoDAO();
            
            
            
            pdao.readForData(sqlDate, sqlDate2);
            
            
            
        } catch (ParseException ex) {
            Logger.getLogger(TelaFaturamento.class.getName()).log(Level.SEVERE, null, ex);
        }
      
  
      
      
      

    }//GEN-LAST:event_btnPesqActionPerformed1


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFaturamento;
    private javax.swing.JTextField txtFatDataAte;
    private javax.swing.JTextField txtFatDataDe;
    // End of variables declaration//GEN-END:variables
}
