/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sys.view;

import br.com.sys.model.bean.Divida;
import br.com.sys.model.bean.Pagamento;
import br.com.sys.model.dao.DividaDAO;
import br.com.sys.model.dao.PagamentoDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ANDRE
 */
public class TelaPagamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaPagamento
     */
    public TelaPagamento() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tablePagamento.getModel();
        tablePagamento.setRowSorter(new TableRowSorter(modelo));
        readTable();
    }
    
    public void readTable() { 
        DefaultTableModel modelo = (DefaultTableModel) tablePagamento.getModel();
        modelo.setNumRows(0);
        PagamentoDAO pdao = new PagamentoDAO();
        
        for (Pagamento p : pdao.read()) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getDivida(),
                p.getDataPagamento(),
                p.getValorPago(),
            });
        }
    }
        public void readJTableIdDaDivida(int divida) {
        
        DefaultTableModel modelo = (DefaultTableModel) tablePagamento.getModel();
        modelo.setNumRows(0);
        PagamentoDAO pdao = new PagamentoDAO();

        for (Pagamento p : pdao.readForIdDivida(divida)) {
            modelo.addRow(new Object[]{
                p.getDivida(),
                p.getDataPagamento(),
                p.getValorPago(),
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIDDividaPag = new javax.swing.JTextField();
        txtValorPago = new javax.swing.JTextField();
        txtDatPag = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPesqPag = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePagamento = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblJuros = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtIdPag = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Pagamento");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID da Dívida:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Valor Pago:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Data do Pagamento:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sys/imagens/sisdebt 185x85.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sys/imagens/add.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sys/imagens/update.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sys/imagens/del.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Pesquisar pagamento:(ID da Dívida)");

        tablePagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Dívida", "Valor Pago", "Data"
            }
        ));
        jScrollPane1.setViewportView(tablePagamento);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Juros:");

        lblJuros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblJuros.setText("0");

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sys/imagens/searche.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed1(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("ID: ");

        txtIdPag.setEditable(false);
        txtIdPag.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(216, 216, 216))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblJuros)
                            .addComponent(txtIDDividaPag, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtValorPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtDatPag, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtIdPag, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtPesqPag, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIdPag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDDividaPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(lblJuros)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesqPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(8, 8, 8)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        setBounds(0, 0, 647, 627);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            Pagamento p = new Pagamento();
            PagamentoDAO dao = new PagamentoDAO();
            Divida d = new Divida();
            DividaDAO daoDiv = new DividaDAO();
            //p = dao.readForIdDividaUnica(Integer.parseInt(txtIDDividaPag.getText()));
            d = daoDiv.readDivida(Integer.parseInt(txtIDDividaPag.getText()));
            SimpleDateFormat formatDate = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date invoiceDate = formatDate.parse(txtDatPag.getText());
            java.sql.Date sqlDate = new java.sql.Date(invoiceDate.getTime());
            
            if(d!= null && d.isPago()){
               JOptionPane.showMessageDialog(null, "Esta dívida já está paga", "ERRO AO PAGAR", ERROR);
            }else{
                if (Double.parseDouble(txtValorPago.getText()) < d.getValorDivida()){
                    JOptionPane.showMessageDialog(null, "O valor digitado é inferior ao valor da dívida", "ERRO AO PAGAR", ERROR);
                }else{
                    // Se a data de atualização for menor que a data de pagamento.
                    if(d.getDataAtualizacao().compareTo(sqlDate) < 0){
                        double multa, juros;
                        multa = Double.parseDouble(txtValorPago.getText()) * 1.02;
                        juros = multa * 1.0035;
                        lblJuros.setText(Double.toString(juros));
                        Divida divida = new Divida();
                        p.setId(Integer.parseInt(txtIdPag.getText()));
                        p.setDivida(new Divida(Integer.parseInt(txtIDDividaPag.getText())));
                        p.setValorPago(juros);
                        p.setDataPagamento(sqlDate);
                        dao.create(p);
                       
//                        txtIDDividaPag.setText("");
//                        txtValorPago.setText("");
//                        txtDatPag.setText("");
//                        
                        readTable();
                    }else{
                       
                        Divida divida = new Divida();
                        divida.setCodigo(Integer.parseInt(txtIDDividaPag.getText()));
                        p.setId(Integer.parseInt(txtIdPag.getText()));
                        p.setDivida(divida);
                        //p.setValorPago(juros);
                        p.setDataPagamento(sqlDate);
                        dao.create(p);
                        txtIDDividaPag.setText("");
                        txtValorPago.setText("");
                        txtDatPag.setText("");
                        
                        readTable();
                    }
                }
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Verifique se o formato da data está correto.", "ERRO AO ADICIONAR", ERROR);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            SimpleDateFormat formatDate = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date invoiceDate = formatDate.parse(txtDatPag.getText());
            java.sql.Date sqlDate = new java.sql.Date(invoiceDate.getTime());
            
            if (tablePagamento.getSelectedRow() != -1 ) {
                
                Pagamento p = new Pagamento();
                PagamentoDAO dao = new PagamentoDAO();
                p.setId((int) tablePagamento.getValueAt(tablePagamento.getSelectedRow(), 0));
                p.setValorPago(Integer.parseInt(txtValorPago.getText()));
                p.setDataPagamento(sqlDate);
                
                dao.update(p);
                
                txtIDDividaPag.setText("");
                txtValorPago.setText("");
                txtDatPag.setText("");
                
                readTable();
                
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Verifique se o formato da data está correto.", "ERRO AO ATUALIZAR", ERROR);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (tablePagamento.getSelectedRow() != -1) {
        Pagamento p = new Pagamento();
        PagamentoDAO dao = new PagamentoDAO();
        p.setId((int) tablePagamento.getValueAt(tablePagamento.getSelectedRow(), 0));
        
        dao.delete(p);
        
        txtIDDividaPag.setText("");
        txtValorPago.setText("");
        txtDatPag.setText("");
        
        readTable();
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnPesquisarActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed1
        // TODO add your handling code here:
        readJTableIdDaDivida(Integer.parseInt(txtPesqPag.getText()));
    }//GEN-LAST:event_btnPesquisarActionPerformed1


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJuros;
    private javax.swing.JTable tablePagamento;
    private javax.swing.JTextField txtDatPag;
    private javax.swing.JTextField txtIDDividaPag;
    private javax.swing.JTextField txtIdPag;
    private javax.swing.JTextField txtPesqPag;
    private javax.swing.JTextField txtValorPago;
    // End of variables declaration//GEN-END:variables
}
